export const SUPERSLAB = [
  { label: '( No Action )', value: 0 },
  { label: 'Left Stick Up', value: 10 },
  { label: 'Left Stick Down', value: 11 },
  { label: 'Left Stick Left', value: 12 },
  { label: 'Left Stick Right', value: 13 },
  { label: 'Face Button 1 (Confirm)', value: 20 },
  { label: 'Face Button 2 (Cancel)', value: 21 },
  { label: 'Face Button 3', value: 22 },
  { label: 'Face Button 4', value: 23 },
  { label: 'Shoulder Button Left', value: 30 },
  { label: 'Shoulder Button Right', value: 31 },
  { label: 'Trigger Left', value: 32 },
  { label: 'Trigger Right', value: 33 },
  { label: 'Start', value: 40 },
  { label: 'Select', value: 41 },
  { label: 'Stick Press Left', value: 50 },
  { label: 'Stick Press Right', value: 51 },
  { label: 'Home', value: 60 },
  { label: 'Capture', value: 61 },
  { label: 'D-Pad Up', value: 80 },
  { label: 'D-Pad Down', value: 81 },
  { label: 'D-Pad Left', value: 82 },
  { label: 'D-Pad Right', value: 83 },
  { label: 'Modifier 1', value: 90 },
  { label: 'Modifier 2', value: 91 },
  { label: 'Modifier 3', value: 92 },
  { label: 'Right Stick Up', value: 100 },
  { label: 'Right Stick Down', value: 101 },
  { label: 'Right Stick Left', value: 102 },
  { label: 'Right Stick Right', value: 103 },
  { label: 'Trigger Left Soft Press', value: 110 },
  { label: 'Trigger Left Medium Press', value: 111 },
  { label: 'Trigger Right Soft Press', value: 112 },
  { label: 'Trigger Right Medium Press', value: 113 },
  { label: 'Mask: Left Stick to D-Pad', value: 121 },
  { label: 'Mask: Right Stick to D-Pad', value: 123 },
  { label: 'Mask: D-Pad to Left Stick', value: 120 },
  { label: 'Mask: D-Pad to Right Stick', value: 122 },
  { label: 'Mask: Left Stick to Right Stick', value: 124 },
  { label: 'Mask: Right Stick to Left Stick', value: 125 },
];

export const getLabelFromValue = (value: number) => {
  const item = SUPERSLAB.find((item) => item.value === value);
  return item ? item.label : '';
};
